/* ************************************************************************** */
/*
/*
/*   fetchBasketDatas.js
/*
/*   By: scoudert <scoudert@student.42.fr>
/*
/*   Created: 2017/09/05 16:34:42 by scoudert
/*   Updated: 2017/09/05 17:21:34 by scoudert
/*
/* ************************************************************************** */
 
/* 
** This is the javascript only file.
** The created and updated date in the header are generated by a script
**  you can rely on them and they are accurate.
*/


function innerHTMLBySelector(selector) {
  let elem = document.querySelector(selector);
  return elem.innerHTML;
}

function fetchItems() {
  const elements = document.querySelectorAll('.cartItem');
  let list = []

  for (let i = 0; i < elements.length; i++) {
    let price = elements[i].querySelector('.price').innerHTML;
    let name = elements[i].querySelector('.itemName').innerHTML;
    let url = elements[i].querySelector('a').getAttribute('href');
    quantity = elements[i].querySelector('.quantity').innerHTML;

    list[i] = {
            "products": {
              "costs": {
                subtotal: price
              },
              "name": name,
                      "url": url,
                  },
                  "quantity": parseInt(quantity)
                }
  }
  return list;
}

let j = {};
j.basket = {}
j.basket.currency = innerHTMLBySelector('span.currency');
j.basket.cost = {subtotal: innerHTMLBySelector('.totals span.price')};
j.basket.items = fetchItems();

//document.querySelector('#result').innerHTML = JSON.stringify(j, null, 4);
console.log(JSON.stringify(j, null, 4));
